sudo: required
language: generic 
services: 
  - docker



before_install:
  - docker build -t kfenech2001/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kfenech2001/docker-react npm run test
